using System.Diagnostics;
using TerraFluent.Html.Reporting.Model;

// A minimal preview/debug harness: builds a report, prints its page count and
// every LayoutResult.Warning (with the structured Reason/ElementType/PageIndex/
// ElementIndex fields, not just the free-form message), writes the HTML to a
// temp file, and opens it in the system's default browser - a faster feedback
// loop than re-running the full sample project just to eyeball one report.
// This is not a new library feature: everything printed here is already
// exposed by ReportDocument/LayoutResult - this is just a better-packaged use
// of it. Swap BuildDemoReport() below for your own document to preview it.

var document = BuildDemoReport();
var layout = TerraFluent.Html.Reporting.Layout.LayoutEngine.Paginate(document);

Console.WriteLine($"{layout.Pages.Count} page(s)");
if (layout.Warnings.Count == 0)
{
    Console.WriteLine("No layout warnings.");
}
else
{
    Console.WriteLine($"{layout.Warnings.Count} layout warning(s):");
    foreach (var warning in layout.Warnings)
    {
        Console.WriteLine(
            $"  page {warning.PageIndex + 1}, element #{warning.ElementIndex} ({warning.ElementType}), " +
            $"reason={warning.Reason}: {warning.Message}");
    }
}

var path = Path.Combine(Path.GetTempPath(), $"terrafluent-preview-{Guid.NewGuid():N}.html");
await document.RenderHtmlDocumentAsync(path);
Console.WriteLine($"Wrote {path}");

try
{
    Process.Start(new ProcessStartInfo(path) { UseShellExecute = true });
    Console.WriteLine("Opened in the default browser.");
}
catch (Exception ex)
{
    Console.WriteLine($"Could not open a browser automatically ({ex.Message}) - open the file above manually.");
}

static ReportDocument BuildDemoReport()
{
    // Deliberately includes an oversized, unsplittable image so the warning
    // path above has something real to print - swap this whole method out
    // for whatever document you actually want to preview.
    return ReportDocument.Create(PageSize.A4)
        .SetMargins(40)
        .Header(h => h.AddText("Preview Harness Demo").AlignCenter().Bold())
        .Footer(f => f.AddPageNumber())
        .Content(c =>
        {
            c.AddHeading("Layout Preview", HeadingLevel.H1);
            c.AddParagraph(
                "This document is generated by the preview harness sample. Replace " +
                "BuildDemoReport() in Program.cs with a call into your own report-building " +
                "code to preview it here instead.");
            c.AddImage(new byte[] { 1 }, "image/png", widthPx: 10, heightPx: 2000).AlignCenter();
        })
        .Build();
}
